export const ENV_KEYS = {
  // Server
  NODE_ENV: 'NODE_ENV',
  SERVER_PORT: 'SERVER_PORT',
  SDK_DOMAIN: 'SDK_DOMAIN',

  // Database
  DATABASE_HOST: 'DATABASE_HOST',
  DATABASE_PORT: 'DATABASE_PORT',
  DATABASE_USER: 'DATABASE_USER',
  DATABASE_PASSWORD: 'DATABASE_PASSWORD',
  DATABASE_NAME: 'DATABASE_NAME',

  // Redis
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',

  // GitHub OAuth
  GITHUB_CLIENT_ID: 'GITHUB_CLIENT_ID',
  GITHUB_CLIENT_SECRET: 'GITHUB_CLIENT_SECRET',
  GITHUB_CALLBACK_URL: 'GITHUB_CALLBACK_URL',

  // Client
  CLIENT_URL: 'CLIENT_URL',

  // JWT
  JWT_ACCESS_SECRET: 'JWT_ACCESS_SECRET',
  JWT_ACCESS_EXPIRES_IN: 'JWT_ACCESS_EXPIRES_IN',
  JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
  JWT_REFRESH_EXPIRES_IN: 'JWT_REFRESH_EXPIRES_IN',

  // AWS S3
  S3_ACCESS_KEY_ID: 'S3_ACCESS_KEY_ID',
  S3_SECRET_ACCESS_KEY: 'S3_SECRET_ACCESS_KEY',
  S3_REGION: 'S3_REGION',
  S3_BUCKET_NAME: 'S3_BUCKET_NAME',
  S3_ENDPOINT: 'S3_ENDPOINT',
} as const;
